# Generated by Django 4.0.3 on 2022-04-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter_ads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
